version: "3"
services:
  testdb:
    image: postgres
    restart: always
    container_name: payment_db
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=mysecretpassword"
      - "POSTGRES_DB=fakeDb"
    ports:
      - 1585:5432
